version: 0.2
phases:
  pre_build:
    commands:
      - aws --version && docker --version && java --version && mvn --version
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - mkdir output
      - cp target/*.jar output/app.jar
      - cp -r ${DEPLOYMENT_NAME}/eb/. output/
      - cd output/ && zip -r ../output.zip . && cd ..
      - aws s3 cp output.zip s3://${ARTIFACT_BUCKET}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/output.zip
      - mv ${DEPLOYMENT_NAME}/infra.yml .

artifacts:
  files:
    - infra.yml

cache:
  paths:
    - /root/.m2/**/*