AWSTemplateFormatVersion: 2010-09-09
Description: A Java SpringBoot application deployed with EC2
Parameters:
  ProjectDeploymentName:
    Type: String
  DeploymentName:
    Type: String
  ApplicationPort:
    Type: String
    Default: 8080
  AlbPort:
    Type: String
    Default: 80
  ASGMinSize:
    Type: Number
    Default: 2
  ASGMaxSize:
    Type: Number
    Default: 4
  InstanceType:
    Type: String
    Default: t2.small
  ProjectVersion:
    Type: String
  ArtifactName:
    Type: String
  LatestAmi2Id:
    Type: String
  AlbAccessLogsEnabled:
    Type: String
    Default: false

Resources:

  Network:
    Type: Atomicity::Vpc::Internet::MODULE

  ##########################
  # ALB
  ##########################

  Alb:
    Properties:
      ApplicationPort: !Ref ApplicationPort
      AlbPort: !Ref AlbPort
      # noinspection YamlUnresolvedReferences
      VPC: !Ref NetworkVPC
      # noinspection YamlUnresolvedReferences
      PublicSubnet1: !Ref NetworkPublicSubnet1
      # noinspection YamlUnresolvedReferences
      PublicSubnet2: !Ref NetworkPublicSubnet2
      HealthCheckPath: /actuator/health
      AccessLogsEnabled: !Ref AlbAccessLogsEnabled
      ProjectDeploymentName: !Ref ProjectDeploymentName
    # noinspection YamlUnresolvedReferences
    DependsOn: NetworkGatewayToInternet
    Type: Atomicity::Alb::Resources::MODULE

  ###################
  # AutoScalingGroup
  ###################

  AutoScalingGroup:
    Properties:
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      MinSize:
        Ref: ASGMinSize
      MaxSize:
        Ref: ASGMaxSize
      LaunchTemplate:
        LaunchTemplateId: !Ref Ec2LaunchTemplate
        Version: !GetAtt Ec2LaunchTemplate.LatestVersionNumber
      # noinspection YamlUnresolvedReferences
      VPCZoneIdentifier: [ !Ref NetworkPrivateSubnet1, !Ref NetworkPrivateSubnet2 ]
      TargetGroupARNs:
        - # noinspection YamlUnresolvedReferences
          Ref: AlbTargetGroup
      Tags:
        - Key: ProjectDeploymentName
          Value: !Ref ProjectDeploymentName
          PropagateAtLaunch: true
        - Key: Name
          Value: !Ref DeploymentName
          PropagateAtLaunch: true
    # By default, when LaunchConfiguration changes, instances are not updated
    # This will trigger new LaunchConfig application on instances.
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: false # Replaces instances inside the same ASG
      AutoScalingRollingUpdate:
        MaxBatchSize: 2 # Specifies the maximum number of instances that CloudFormation updates.
        MinInstancesInService: 2 # must be less than Asg MaxSize
        WaitOnResourceSignals: true # Specifies whether the Cloudformation waits on signals from new instances during an update.
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Type: AWS::AutoScaling::AutoScalingGroup

  Ec2LaunchTemplate:
    Properties:
      LaunchTemplateName: !Ref ProjectDeploymentName
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt WebappInstanceProfile.Arn
        ImageId: !Ref LatestAmi2Id
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !GetAtt WebappSecurityGroup.GroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource AutoScalingGroup --region ${AWS::Region}
    Type: AWS::EC2::LaunchTemplate

  WebappSecurityGroup:
    Properties:
      GroupDescription: allow access to Webapp from Alb
      # noinspection YamlUnresolvedReferences
      VpcId: !Ref NetworkVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ApplicationPort
          ToPort: !Ref ApplicationPort
          # noinspection YamlUnresolvedReferences
          SourceSecurityGroupId: !Ref AlbSecurityGroup
    Type: AWS::EC2::SecurityGroup

  Ec2CodeDeployRole:
    Properties:
      Description: Role applied on Instance Profile via launch template. Provides full access to CodeDeploy resources.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: code-deploy-launch-template-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:CreateTags
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:PutRetentionPolicy
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Path: /
    Type: AWS::IAM::Role

  WebappInstanceProfile:
    Properties:
      Roles:
        - !Ref Ec2CodeDeployRole
    Type: AWS::IAM::InstanceProfile

  ScalingPolicy:
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: '50'
    Type: AWS::AutoScaling::ScalingPolicy

  ###############
  # VPC Endpoints
  ###############

  VpcEndPoints:
    Properties:
      # noinspection YamlUnresolvedReferences
      VPC: !Ref NetworkVPC
      # noinspection YamlUnresolvedReferences
      PrivateSubnet1: !Ref NetworkPrivateSubnet1
      # noinspection YamlUnresolvedReferences
      PrivateSubnet2: !Ref NetworkPrivateSubnet2
    Type: Atomicity::Vpc::Endpoints::MODULE

Outputs:
  WatchServiceEndpoint:
    Value: !Sub
      - "http://${LbDNSName}/${DeploymentName}"
      - # noinspection YamlUnresolvedReferences
        LbDNSName: !GetAtt AlbInstance.DNSName