AWSTemplateFormatVersion: 2010-09-09
Description: A Java SpringBoot application deployed on ECS Fargate behind an ALB
Parameters:
  ProjectDeploymentName:
    Type: String
  DeploymentName:
    Type: String
  ProjectVersion:
    Type: String
  ApplicationPort:
    Type: String
    Default: 8080
  DesiredCount:
    Type: String
    Default: 2
  AlbPort:
    Type: String
    Default: 80
  ContainerImageRepositoryUrl:
    Type: String
  AlbAccessLogsEnabled:
    Type: String
    Default: false

Resources:

  Network:
    Type: Atomicity::Vpc::Internet::MODULE

  ##########################
  # ALB
  ##########################

  Alb:
    Properties:
      ApplicationPort: !Ref ApplicationPort
      AlbPort: !Ref AlbPort
      # noinspection YamlUnresolvedReferences
      VPC: !Ref NetworkVPC
      # noinspection YamlUnresolvedReferences
      PublicSubnet1: !Ref NetworkPublicSubnet1
      # noinspection YamlUnresolvedReferences
      PublicSubnet2: !Ref NetworkPublicSubnet2
      HealthCheckPath: /actuator/health
      TargetType: ip
      AccessLogsEnabled: !Ref AlbAccessLogsEnabled
      ProjectDeploymentName: !Ref ProjectDeploymentName
    # noinspection YamlUnresolvedReferences
    DependsOn: NetworkGatewayToInternet
    Type: Atomicity::Alb::Resources::MODULE

  ##########################
  # ECS
  ##########################

  ECSExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: [ ecs-tasks.amazonaws.com ]
          Action: [ sts:AssumeRole ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
    Type: AWS::IAM::Role

  ECSTaskRole:
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub ${ProjectDeploymentName}-ecs-task-info
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - ecs:DescribeTasks
                  - ecs:ListTasks
        - PolicyName: !Sub ${ProjectDeploymentName}-s3-upload
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource:
                  - !Sub "arn:aws:s3:::${ProjectDeploymentName}/*"
                  - !Sub "arn:aws:s3:::${ProjectDeploymentName}"
                Effect: Allow
                Action: "s3:*"
        - PolicyName: !Sub ${ProjectDeploymentName}-ecs-service-info
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${ProjectDeploymentName}/${ProjectDeploymentName}"
                Effect: Allow
                Action:
                  - ecs:ListServices
                  - ecs:DescribeServices
        - PolicyName: !Sub ${ProjectDeploymentName}-parameter-store
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:DescribeParameters'
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                Resource: '*'
    Type: AWS::IAM::Role

  EcsFargateSecurityGroup:
    Properties:
      GroupDescription: allow access to ECS from ALB
      # noinspection YamlUnresolvedReferences
      VpcId: !Ref NetworkVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ApplicationPort
          ToPort: !Ref ApplicationPort
          # noinspection YamlUnresolvedReferences
          SourceSecurityGroupId: !Ref AlbSecurityGroup
    Type: AWS::EC2::SecurityGroup

  EcsFargateLogGroup:
    Properties:
      LogGroupName: !Sub /ecs/fargate/${ProjectDeploymentName}
      RetentionInDays: 90
    Type: AWS::Logs::LogGroup

  EcsFargateTaskDefinition:
    # ECS Task Definition
    Properties:
      NetworkMode: awsvpc
      Family: !Ref ProjectDeploymentName
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn # Fargate requires task definition to have execution role ARN to support ECR images
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref ProjectDeploymentName
          Image: !Sub ${ContainerImageRepositoryUrl}:${ProjectVersion}
          Environment:
            - Name: SERVER_PORT
              Value: !Ref ApplicationPort
            - Name: SPRING_PROFILES_ACTIVE
              Value: !Ref DeploymentName
            - Name: PROJECT_DEPLOYMENT_NAME
              Value: !Ref ProjectDeploymentName
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref EcsFargateLogGroup
              awslogs-stream-prefix: oam-ecs
          PortMappings:
            - ContainerPort: !Ref ApplicationPort
    Type: AWS::ECS::TaskDefinition

  EcsFargateCluster:
    # ECS Cluster
    Properties:
      ClusterName: !Ref ProjectDeploymentName
    Type: AWS::ECS::Cluster

  # Baseline traffic processed with OnDemand
  # Peak handled by instances with 25% On Demand 75% Spot ratio
  EcsEc2ClusterCPAssociation:
    Properties:
      Cluster: !Ref EcsFargateCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      # Can be set at ECS Service level also
      DefaultCapacityProviderStrategy:
        - Base: !Ref DesiredCount
          CapacityProvider: FARGATE
          Weight: 1
        - Base: 0
          CapacityProvider: FARGATE_SPOT
          Weight: 4
    Type: AWS::ECS::ClusterCapacityProviderAssociations

  EcsFargateService:
    # ECS Service
    Properties:
      ServiceName: !Ref ProjectDeploymentName
      Cluster: !Ref EcsFargateCluster
      DesiredCount: !Ref DesiredCount
      LoadBalancers:
        - # noinspection YamlUnresolvedReferences
          TargetGroupArn: !Ref AlbTargetGroup # loadBalancerName and targetGroupArn cannot both be specified. You must specify either a loadBalancerName or a targetGroupArn.
          ContainerPort: !Ref ApplicationPort
          ContainerName: !Ref ProjectDeploymentName
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref EcsFargateSecurityGroup
          # noinspection YamlUnresolvedReferences
          Subnets: [ !Ref NetworkPrivateSubnet1, !Ref NetworkPrivateSubnet2 ]
      TaskDefinition: !Ref 'EcsFargateTaskDefinition'
    # noinspection YamlUnresolvedReferences
    DependsOn:
      - AlbListener # unless "The target group does not have an associated load balancer"
      - EcsFargateLogGroup
    Type: AWS::ECS::Service

  #####################
  # ECS Service Scaling
  #####################

  # https://containersonaws.com/pattern/scale-ecs-service-cloudformation

  # Role that Application Auto Scaling will use to interact with
  # CloudWatch and Amazon ECS
  AutoscalingRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ application-autoscaling.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: service-autoscaling
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'application-autoscaling:*'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'ecs:DescribeServices'
                  - 'ecs:UpdateService'
                Resource: '*'
    Type: AWS::IAM::Role

  # Enable autoscaling for the service
  ScalableTarget:
    Properties:
      ServiceNamespace: 'ecs'
      ScalableDimension: 'ecs:service:DesiredCount'
      ResourceId: !Sub
        - service/${ClusterName}/${ServiceName}
        - ClusterName: !Ref EcsFargateCluster
          ServiceName: !GetAtt EcsFargateService.Name
      MinCapacity: 2
      MaxCapacity: 10
      RoleARN: !GetAtt AutoscalingRole.Arn
    Type: AWS::ApplicationAutoScaling::ScalableTarget

  # Create scaling policies that describe how to scale the service up and down.
  ScaleDownPolicy:
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub
        - 'scale-${ClusterName}-down'
        - ClusterName: !Ref EcsFargateCluster
      PolicyType: StepScaling
      ResourceId: !Sub
        - 'service/${ClusterName}/${ServiceName}'
        - ClusterName: !Ref EcsFargateCluster
          ServiceName: !GetAtt EcsFargateService.Name
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        AdjustmentType: 'ChangeInCapacity'
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1
        MetricAggregationType: 'Average'
        Cooldown: 60
    Type: AWS::ApplicationAutoScaling::ScalingPolicy

  ScaleUpPolicy:
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub
        - 'scale-${ClusterName}-up'
        - ClusterName: !Ref EcsFargateCluster
      PolicyType: StepScaling
      ResourceId: !Sub
        - 'service/${ClusterName}/${ServiceName}'
        - ClusterName: !Ref EcsFargateCluster
          ServiceName: !GetAtt EcsFargateService.Name
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        AdjustmentType: 'ChangeInCapacity'
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 15
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 15
            MetricIntervalUpperBound: 25
            ScalingAdjustment: 2
          - MetricIntervalLowerBound: 25
            ScalingAdjustment: 3
        MetricAggregationType: 'Average'
        Cooldown: 60
    Type: AWS::ApplicationAutoScaling::ScalingPolicy

  # Create alarms to trigger the scaling policies
  LowCpuUsageAlarm:
    Properties:
      AlarmName: !Sub
        - 'low-cpu-${ClusterName}'
        - ClusterName: !Ref EcsFargateCluster
      AlarmDescription: !Sub
        - "Low CPU utilization for service ${ClusterName}"
        - ClusterName: !Ref EcsFargateCluster
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt EcsFargateService.Name
        - Name: ClusterName
          Value: !Ref EcsFargateCluster
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleDownPolicy
    Type: AWS::CloudWatch::Alarm

  HighCpuUsageAlarm:
    Properties:
      AlarmName: !Sub
        - 'high-cpu-${ClusterName}'
        - ClusterName: !Ref EcsFargateCluster
      AlarmDescription: !Sub
        - "High CPU utilization for service ${ClusterName}"
        - ClusterName: !Ref EcsFargateCluster
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt EcsFargateService.Name
        - Name: ClusterName
          Value: !Ref EcsFargateCluster
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleUpPolicy
    Type: AWS::CloudWatch::Alarm

  EnableStressParameter:
    Properties:
      DataType: text
      Name: /custom/stress
      Type: String
      Value: false
    Type: AWS::SSM::Parameter

  ###############
  # VPC Endpoints
  ###############

  VpcEndPoints:
    Properties:
      # noinspection YamlUnresolvedReferences
      VPC: !Ref NetworkVPC
      # noinspection YamlUnresolvedReferences
      PrivateSubnet1: !Ref NetworkPrivateSubnet1
      # noinspection YamlUnresolvedReferences
      PrivateSubnet2: !Ref NetworkPrivateSubnet2
    Type: Atomicity::Vpc::Endpoints::MODULE

Outputs:
  WatchServiceEndpoint:
    Value: !Sub
      - "http://${LbDNSName}/${DeploymentName}"
      - # noinspection YamlUnresolvedReferences
        LbDNSName: !GetAtt AlbInstance.DNSName