version: 0.2
phases:
  pre_build:
    commands:
      - aws --version && docker --version && java --version && mvn --version
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - cp target/*.jar app.jar
      - aws s3 cp app.jar s3://${ARTIFACT_BUCKET}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/app.jar
      - zip -r ${DEPLOYMENT_NAME}/spring_boot_cookbook.zip ${DEPLOYMENT_NAME}/spring_boot_cookbook
      - aws s3 cp ${DEPLOYMENT_NAME}/spring_boot_cookbook.zip s3://${ARTIFACT_BUCKET}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/spring_boot_cookbook.zip

artifacts:
  files:
    - ${DEPLOYMENT_NAME}/infra.yml
  discard-paths: yes

cache:
  paths:
    - /root/.m2/**/*