---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
  namespace: ${K8S_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: ${AMAZON_EKS_LOAD_BALANCER_CONTROLLER_ROLE_ARN}
