name: ec2-image-builder-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ROLE_NAME: GitHubActionsRole
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CICD_ACCOUNT_ID: ${{ secrets.CICD_ACCOUNT_ID }}
  PROD_ACCOUNT_ID: ${{ secrets.PROD_ACCOUNT_ID }}
  AWS_ORGANIZATION_ID: ${{ secrets.AWS_ORGANIZATION_ID }}
  AWS_ORGANIZATION_UNIT_ID: ${{ secrets.AWS_ORGANIZATION_UNIT_ID }}
  AWS_GITHUB_CONNECTION_ARN: ${{ secrets.AWS_GITHUB_CONNECTION_ARN }}
  PROJECT_NAME:  'aws-codepipeline-boot-2'
  DEPLOYMENT_NAME: 'ec2-image-builder'
  PROJECT_DEPLOYMENT_NAME: 'aws-codepipeline-boot-2-ec2-image-builder'

jobs:
  deploy-fargate-app:
    environment: production
    name: Deploy (CICD account)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (PROD account)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CICD_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: infra/cdk/package-lock.json

      - name: Install dependencies
        working-directory: infra/cdk
        run: npm ci

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy app
        working-directory: infra/cdk
        run: |
          cdk deploy \
            --app "npx ts-node --prefer-ts-exts bin/${{ env.DEPLOYMENT_NAME }}/cdk.ts" \
            --require-approval never \
            ${{ env.DEPLOYMENT_NAME }} \
            --exclusively